/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgreementsRouteImport } from './routes/agreements'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CountriesRouteImport } from './routes/countries'
import { Route as MapRouteImport } from './routes/map'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CountriesIndexRouteImport } from './routes/countries/index'
import { Route as CountryCountryIdRouteImport } from './routes/country.$countryId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementsRoute = AgreementsRouteImport.update({
  id: '/agreements',
  path: '/agreements',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesRoute = CountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesIndexRoute = CountriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CountriesRoute,
} as any)
const CountryCountryIdRoute = CountryCountryIdRouteImport.update({
  id: '/country/$countryId',
  path: '/country/$countryId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agreements': typeof AgreementsRoute
  '/audit': typeof AuditRoute
  '/contacts': typeof ContactsRoute
  '/countries': typeof CountriesRouteWithChildren
  '/map': typeof MapRoute
  '/meetings': typeof MeetingsRoute
  '/settings': typeof SettingsRoute
  '/country/$countryId': typeof CountryCountryIdRoute
  '/countries/': typeof CountriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agreements': typeof AgreementsRoute
  '/audit': typeof AuditRoute
  '/contacts': typeof ContactsRoute
  '/map': typeof MapRoute
  '/meetings': typeof MeetingsRoute
  '/settings': typeof SettingsRoute
  '/country/$countryId': typeof CountryCountryIdRoute
  '/countries': typeof CountriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agreements': typeof AgreementsRoute
  '/audit': typeof AuditRoute
  '/contacts': typeof ContactsRoute
  '/countries': typeof CountriesRouteWithChildren
  '/map': typeof MapRoute
  '/meetings': typeof MeetingsRoute
  '/settings': typeof SettingsRoute
  '/country/$countryId': typeof CountryCountryIdRoute
  '/countries/': typeof CountriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agreements'
    | '/audit'
    | '/contacts'
    | '/countries'
    | '/map'
    | '/meetings'
    | '/settings'
    | '/country/$countryId'
    | '/countries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agreements'
    | '/audit'
    | '/contacts'
    | '/map'
    | '/meetings'
    | '/settings'
    | '/country/$countryId'
    | '/countries'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agreements'
    | '/audit'
    | '/contacts'
    | '/countries'
    | '/map'
    | '/meetings'
    | '/settings'
    | '/country/$countryId'
    | '/countries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgreementsRoute: typeof AgreementsRoute
  AuditRoute: typeof AuditRoute
  ContactsRoute: typeof ContactsRoute
  CountriesRoute: typeof CountriesRouteWithChildren
  MapRoute: typeof MapRoute
  MeetingsRoute: typeof MeetingsRoute
  SettingsRoute: typeof SettingsRoute
  CountryCountryIdRoute: typeof CountryCountryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreements': {
      id: '/agreements'
      path: '/agreements'
      fullPath: '/agreements'
      preLoaderRoute: typeof AgreementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries': {
      id: '/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof CountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/': {
      id: '/countries/'
      path: '/'
      fullPath: '/countries/'
      preLoaderRoute: typeof CountriesIndexRouteImport
      parentRoute: typeof CountriesRoute
    }
    '/country/$countryId': {
      id: '/country/$countryId'
      path: '/country/$countryId'
      fullPath: '/country/$countryId'
      preLoaderRoute: typeof CountryCountryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CountriesRouteChildren {
  CountriesIndexRoute: typeof CountriesIndexRoute
}

const CountriesRouteChildren: CountriesRouteChildren = {
  CountriesIndexRoute: CountriesIndexRoute,
}

const CountriesRouteWithChildren = CountriesRoute._addFileChildren(
  CountriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgreementsRoute: AgreementsRoute,
  AuditRoute: AuditRoute,
  ContactsRoute: ContactsRoute,
  CountriesRoute: CountriesRouteWithChildren,
  MapRoute: MapRoute,
  MeetingsRoute: MeetingsRoute,
  SettingsRoute: SettingsRoute,
  CountryCountryIdRoute: CountryCountryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
